name: iOS Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build, Lint and Test
    runs-on: macos-14

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🍏 Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: 🛠️ Install SwiftLint
        run: brew install swiftlint

      - name: 🧪 Run Tests (and Lint via Build Phases)
        run: make test
